# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [ ]:
import torch

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [ ]:
torch.tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 )

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [ ]:
x = torch.arange(2,21,2)
y = x*(x+1)
y

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [ ]:
x = torch.arange(1,108)
x= x[x%10 !=8]
x= x[x%10 !=9]
x= x[x%10 !=0]
x = torch.split(x, 7)
x

(tensor([1, 2, 3, 4, 5, 6, 7]),
 tensor([11, 12, 13, 14, 15, 16, 17]),
 tensor([21, 22, 23, 24, 25, 26, 27]),
 tensor([31, 32, 33, 34, 35, 36, 37]),
 tensor([41, 42, 43, 44, 45, 46, 47]),
 tensor([51, 52, 53, 54, 55, 56, 57]),
 tensor([61, 62, 63, 64, 65, 66, 67]),
 tensor([71, 72, 73, 74, 75, 76, 77]),
 tensor([81, 82, 83, 84, 85, 86, 87]),
 tensor([91, 92, 93, 94, 95, 96, 97]),
 tensor([101, 102, 103, 104, 105, 106, 107]))

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [ ]:
torch.tensor([[0,1],[2,3]]).repeat(3, 4)[:3, :4]

tensor([[0, 1, 0, 1],
        [2, 3, 2, 3],
        [0, 1, 0, 1]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

In [ ]:
m = torch.randint(low=0, high=20, size=(4,7))
m
a = 0
b = 20
normalized_dataset = (m - torch.min(m)) / (torch.max(m) - torch.min(m))
print(normalized_dataset)

tensor([[0.0526, 0.1579, 0.1579, 0.4211, 0.0000, 0.2105, 0.8421],
        [0.7368, 0.6316, 0.8947, 0.6316, 0.5789, 0.2632, 1.0000],
        [0.1579, 0.0000, 0.6842, 0.4211, 0.8947, 0.5263, 0.0000],
        [0.1053, 0.4211, 1.0000, 0.2105, 0.8947, 0.5789, 0.8947]])


1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в тензорах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [ ]:
a = 0
b = 10
ar1 = torch.randint(low=a, high=b, size=(4,7))
ar2 = torch.randint(low=a, high=b, size=(4,7))
print(ar1)
print(ar2)
arr3 = torch.where(ar1>ar2, ar1,ar2)
arr3

tensor([[2, 4, 4, 8, 5, 1, 2],
        [4, 0, 9, 9, 7, 4, 7],
        [6, 6, 5, 7, 0, 5, 0],
        [1, 7, 4, 8, 1, 2, 0]])
tensor([[4, 8, 8, 1, 4, 8, 9],
        [7, 6, 3, 0, 0, 3, 7],
        [2, 8, 3, 0, 5, 5, 7],
        [6, 1, 0, 0, 2, 2, 3]])


tensor([[4, 8, 8, 8, 5, 8, 9],
        [7, 6, 9, 9, 7, 4, 7],
        [6, 8, 5, 7, 5, 5, 7],
        [6, 7, 4, 8, 2, 2, 3]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [ ]:
df = torch.randint(0,100,size = [1,20])
print(df)
torch.kthvalue(df, 2)[0]# find 3 largest element from the tensor

tensor([[82, 56, 99, 43, 53, 26, 38, 84, 57, 58, 21, 48, 62, 44, 30, 44, 82, 17,
         40, 12]])


tensor([17])

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [ ]:
x = torch.arange(1,108)
x= x[x%10 !=8]
x= x[x%10 !=9]
x= x[x%10 !=0]
x = torch.split(x, 7)
x

(tensor([1, 2, 3, 4, 5, 6, 7]),
 tensor([11, 12, 13, 14, 15, 16, 17]),
 tensor([21, 22, 23, 24, 25, 26, 27]),
 tensor([31, 32, 33, 34, 35, 36, 37]),
 tensor([41, 42, 43, 44, 45, 46, 47]),
 tensor([51, 52, 53, 54, 55, 56, 57]),
 tensor([61, 62, 63, 64, 65, 66, 67]),
 tensor([71, 72, 73, 74, 75, 76, 77]),
 tensor([81, 82, 83, 84, 85, 86, 87]),
 tensor([91, 92, 93, 94, 95, 96, 97]),
 tensor([101, 102, 103, 104, 105, 106, 107]))

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [ ]:
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])
for i in range(0,3):
  a_2d[i]= a_2d[i] - b_1d[i]
a_2d

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
tensor([1, 3, 5, 7])
```

In [ ]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])
torch.where(a == b)[0]

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
tensor([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [ ]:
a = torch.arange(9).view(3,3)
a = torch.flip(a, [0, 1])
a

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
```

Ожидается результат:

```python
tensor([6, 9, 10])
```

In [ ]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
a = a[a>5]
a[a<=10]

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `torch.arange(9).reshape(3,3)`

In [ ]:
a = torch.arange(9).reshape(3,3)
print(a)
a[:,[1, 2]]= a[:,[2,1 ]]
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
a = torch.randint(0,10, (8, 10))
print(a)
result = torch.min(torch.sum(a, 1), dim=0, keepdim=False)
print(result.values)
a[result.indices]


tensor([[2, 0, 7, 4, 4, 0, 8, 7, 0, 5],
        [3, 5, 0, 5, 6, 7, 3, 8, 3, 8],
        [6, 1, 9, 6, 5, 3, 7, 1, 0, 9],
        [2, 1, 0, 3, 4, 8, 7, 1, 7, 5],
        [6, 0, 8, 2, 8, 7, 0, 1, 8, 2],
        [8, 5, 6, 9, 2, 5, 5, 3, 8, 4],
        [8, 6, 7, 3, 5, 3, 5, 5, 6, 3],
        [0, 8, 9, 8, 0, 3, 0, 1, 4, 3]])
tensor(36)


tensor([0, 8, 9, 8, 0, 3, 0, 1, 4, 3])

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [ ]:
df = torch.randint(0,100,size = [1,20])
torch.clamp(df, min=30, max=70)

tensor([[38, 30, 36, 70, 70, 70, 49, 30, 70, 70, 50, 70, 68, 66, 30, 30, 60, 70,
         70, 64]])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [ ]:
a = 0
b = 10
ar1 = torch.randint(low=a, high=b, size=(30,3))
ar2 = torch.randint(low=a, high=b, size=(30,3))
torch.where(ar1>ar2,ar1,0).sum()

tensor(241)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

**ДОДЕЛАТЬ**

In [ ]:
df = torch.randint(low=0, high=10, size=(20,20))
df.flatten()[1::21]

tensor([4, 8, 4, 1, 8, 5, 7, 5, 6, 7, 1, 1, 3, 0, 3, 4, 7, 1, 5])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [ ]:
a = 0
b = 10
ar1 = torch.randint(low=a, high=b, size=(5,10))
print(ar1)
ar2 = torch.randint(low=a, high=b, size=(5,10))
print(ar2)
torch.where(ar1==ar2,ar1*2,ar1)

tensor([[8, 2, 1, 2, 9, 2, 9, 5, 4, 0],
        [8, 9, 0, 9, 4, 3, 8, 7, 1, 9],
        [0, 8, 7, 5, 3, 9, 5, 6, 9, 1],
        [8, 9, 8, 6, 7, 1, 6, 7, 8, 3],
        [3, 9, 9, 6, 9, 2, 5, 7, 5, 0]])
tensor([[5, 1, 7, 8, 3, 1, 6, 8, 8, 9],
        [2, 4, 4, 3, 4, 0, 2, 3, 7, 9],
        [4, 2, 5, 8, 2, 8, 6, 2, 8, 5],
        [9, 5, 9, 1, 0, 7, 7, 4, 9, 0],
        [9, 3, 3, 4, 5, 5, 4, 2, 1, 4]])


tensor([[ 8,  2,  1,  2,  9,  2,  9,  5,  4,  0],
        [ 8,  9,  0,  9,  8,  3,  8,  7,  1, 18],
        [ 0,  8,  7,  5,  3,  9,  5,  6,  9,  1],
        [ 8,  9,  8,  6,  7,  1,  6,  7,  8,  3],
        [ 3,  9,  9,  6,  9,  2,  5,  7,  5,  0]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [ ]:
a = 0
b = 10
size =(4,7)
ar1 = torch.randint(low=a, high=b, size=size)
print(ar1)
ar2 = torch.randint(low=a, high=b, size=size)
print(ar2)
ar3 = torch.randint(low=a, high=b, size=size)
print(ar3)

torch.where((ar1>ar2) & (ar1<ar3),0,ar1)

tensor([[3, 3, 7, 0, 6, 7, 5],
        [6, 7, 9, 1, 4, 6, 4],
        [7, 2, 8, 6, 3, 3, 0],
        [5, 9, 6, 8, 9, 3, 9]])
tensor([[9, 6, 3, 5, 8, 2, 2],
        [4, 3, 1, 5, 1, 9, 1],
        [9, 6, 4, 4, 9, 6, 7],
        [3, 7, 2, 1, 5, 8, 8]])
tensor([[8, 6, 4, 2, 6, 4, 1],
        [3, 1, 3, 3, 6, 4, 7],
        [9, 4, 3, 4, 0, 6, 8],
        [3, 9, 4, 9, 6, 7, 3]])


tensor([[3, 3, 7, 0, 6, 7, 5],
        [6, 7, 9, 1, 0, 6, 0],
        [7, 2, 8, 6, 3, 3, 0],
        [5, 9, 6, 0, 9, 3, 9]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [ ]:
#Старое решение
from collections import Counter
a = 0
b = 20
size =(20,5)
ar1 = torch.randint(low=a, high=b, size=size)
print(ar1)
_, indeces = torch.max(ar1, 1)

c = Counter(indeces.numpy())
print(c)
for key, value in c.items():
  if value>=5:
    print("Строка: ",key)

tensor([[13, 12, 10,  9,  6],
        [ 6,  4,  3,  2, 16],
        [10, 16, 13,  7, 12],
        [ 4,  2,  2,  0,  1],
        [13,  2, 12,  5,  2],
        [18,  9,  4,  3, 12],
        [ 2, 10, 18,  6, 10],
        [12,  0,  7, 13,  7],
        [16,  7, 17,  6,  2],
        [ 7, 10, 18, 10, 19],
        [ 3,  5, 14, 10,  1],
        [ 1,  6, 18,  6, 16],
        [ 0,  6, 14, 16,  5],
        [16,  1, 17, 13,  6],
        [ 9, 13,  0, 10, 13],
        [12,  0,  7,  8,  9],
        [ 0,  1, 14, 17, 16],
        [11, 15,  1,  7, 14],
        [ 9,  9, 18, 14,  5],
        [18, 15,  3, 12,  9]])
Counter({0: 6, 2: 6, 1: 3, 3: 3, 4: 2})
Строка:  0
Строка:  2


In [ ]:
#Новое решение
ar1_max = torch.where(ar1 == ar1.max(dim=1)[0].view(-1, 1), 1, 0)
ar1_max

tensor([[1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0]])

In [ ]:
ar1_max.sum(dim=0)

tensor([6, 3, 6, 3, 3])

In [ ]:
(ar1_max.sum(dim=0) >=5).nonzero(as_tuple=True)[0]

tensor([0, 2])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива.

In [ ]:
a = 0
b = 1
size =(4,7)
ar1 = torch.randint(low=a, high=b+1, size=size)
print(ar1)

tensor([[0, 1, 0, 1, 0, 0, 0],
        [0, 1, 1, 0, 1, 0, 0],
        [1, 0, 1, 1, 1, 1, 1],
        [0, 1, 0, 0, 0, 0, 1]])


1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [ ]:
t1 = torch.tensor([2, 3, 2, 2, 2, 1])
t1

tensor([2, 3, 2, 2, 2, 1])

In [ ]:
t2 = torch.zeros(t1.size()[0], t1.max()+1)
t2

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
t2[torch.arange(t1.size()[0]), t1] = 1
t2[:, 1:]

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре.
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая.

In [ ]:
ar1 = torch.randint(0, 100, (20, ))

ar1

tensor([75, 34, 89, 64, 54, 17, 74, 82, 55, 91, 49, 20,  2, 98, 17, 82, 69, 45,
        74, 48])

In [ ]:
val = torch.bincount(ar1).argmax()
val

tensor(17)

In [ ]:
(ar1 == val).nonzero().flatten()

tensor([ 5, 14])

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [ ]:
X = torch.arange(0, 10, 0.01)
Y = X * torch.sin(X)
mask_05 = Y > 0.5

In [ ]:
mask_split = ((X[mask_05][1:] - X[mask_05][:-1]) > 0.1).nonzero()
X_masked = X[mask_05][1:]

In [ ]:
X_masked[0], X_masked[mask_split[0]-1], X_masked[mask_split[0]], X_masked[-1]

(tensor(0.7600), tensor([2.9700]), tensor([6.3700]), tensor(9.3700))

In [ ]:
X_masked

tensor([0.7600, 0.7700, 0.7800, 0.7900, 0.8000, 0.8100, 0.8200, 0.8300, 0.8400,
        0.8500, 0.8600, 0.8700, 0.8800, 0.8900, 0.9000, 0.9100, 0.9200, 0.9300,
        0.9400, 0.9500, 0.9600, 0.9700, 0.9800, 0.9900, 1.0000, 1.0100, 1.0200,
        1.0300, 1.0400, 1.0500, 1.0600, 1.0700, 1.0800, 1.0900, 1.1000, 1.1100,
        1.1200, 1.1300, 1.1400, 1.1500, 1.1600, 1.1700, 1.1800, 1.1900, 1.2000,
        1.2100, 1.2200, 1.2300, 1.2400, 1.2500, 1.2600, 1.2700, 1.2800, 1.2900,
        1.3000, 1.3100, 1.3200, 1.3300, 1.3400, 1.3500, 1.3600, 1.3700, 1.3800,
        1.3900, 1.4000, 1.4100, 1.4200, 1.4300, 1.4400, 1.4500, 1.4600, 1.4700,
        1.4800, 1.4900, 1.5000, 1.5100, 1.5200, 1.5300, 1.5400, 1.5500, 1.5600,
        1.5700, 1.5800, 1.5900, 1.6000, 1.6100, 1.6200, 1.6300, 1.6400, 1.6500,
        1.6600, 1.6700, 1.6800, 1.6900, 1.7000, 1.7100, 1.7200, 1.7300, 1.7400,
        1.7500, 1.7600, 1.7700, 1.7800, 1.7900, 1.8000, 1.8100, 1.8200, 1.8300,
        1.8400, 1.8500, 1.8600, 1.8700, 

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [ ]:
a = torch.arange(1, 100).reshape(99, 1)
b = torch.arange(1, 100).repeat(99, 1)
print(a,b)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39],
        [40],
        [41],
        [42],
        [43],
        [44],
        [45],
        [46],
        [47],
        [48],
        [49],
        [50],
        [51],
        [52],
        [53],
        [54],
        [55],
        [56],
        [57],
        [58],
        [59],
        [60],
        [61],
        [62],
        [63],
        [64],
        [65],
        [66],
        [67],
        [68],
        [69],
        [70],
        [71],
      

In [ ]:
a % b

tensor([[ 0,  1,  1,  ...,  1,  1,  1],
        [ 0,  0,  2,  ...,  2,  2,  2],
        [ 0,  1,  0,  ...,  3,  3,  3],
        ...,
        [ 0,  1,  1,  ...,  0, 97, 97],
        [ 0,  0,  2,  ...,  1,  0, 98],
        [ 0,  1,  0,  ...,  2,  1,  0]])

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [ ]:
a = torch.tensor([1, 1])
b = torch.tensor([2, 2])

torch.sqrt(torch.pow(b - a, 2))

tensor([1., 1.])

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100.
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [ ]:
#Старое решение
df = torch.randint(0, 100, (20, 3))
len = torch.sqrt(torch.pow(df, 2).sum(1))
print(len)
torch.tensor([
    x[0]
    for x in sorted(list(zip(df.cpu().detach().numpy().tolist(), len.cpu().detach().numpy())), key = lambda x: x[1])
  ])

tensor([ 72.2634,  90.7855,  46.2385,  96.0156, 120.2705,  89.0000,  56.5420,
         78.3135, 108.1018, 117.5840, 107.0467, 106.8363, 126.4160,  88.1079,
         98.6205, 100.2896,  89.6939, 103.7882, 116.3658,  45.3982])


tensor([[ 2, 11, 44],
        [19, 39, 16],
        [44,  6, 35],
        [55,  9, 46],
        [18, 60, 47],
        [65, 17, 57],
        [36, 15, 80],
        [22, 75, 44],
        [ 9, 81, 40],
        [37, 31, 83],
        [58, 11, 79],
        [15, 92, 37],
        [46, 84, 40],
        [62, 53, 69],
        [ 5, 45, 97],
        [81, 63, 34],
        [39, 68, 86],
        [87,  4, 79],
        [65, 96, 32],
        [59, 76, 82]])

In [ ]:
#Новое решение

In [ ]:
torch.sort(len)

torch.return_types.sort(
values=tensor([ 45.3982,  46.2385,  56.5420,  72.2634,  78.3135,  88.1079,  89.0000,
         89.6939,  90.7855,  96.0156,  98.6205, 100.2896, 103.7882, 106.8363,
        107.0467, 108.1018, 116.3658, 117.5840, 120.2705, 126.4160]),
indices=tensor([19,  2,  6,  0,  7, 13,  5, 16,  1,  3, 14, 15, 17, 11, 10,  8, 18,  9,
         4, 12]))

In [ ]:
df[torch.sort(len)[1]]

tensor([[ 2, 11, 44],
        [19, 39, 16],
        [44,  6, 35],
        [55,  9, 46],
        [18, 60, 47],
        [65, 17, 57],
        [36, 15, 80],
        [22, 75, 44],
        [ 9, 81, 40],
        [37, 31, 83],
        [58, 11, 79],
        [15, 92, 37],
        [46, 84, 40],
        [62, 53, 69],
        [ 5, 45, 97],
        [81, 63, 34],
        [39, 68, 86],
        [87,  4, 79],
        [65, 96, 32],
        [59, 76, 82]])

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [ ]:
#Старое решение
t = torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])
index = []
for i in range(t.shape[0] - 2):
  a, b, c = t[i:i+3]
  if b > a and b > c:
    index.append(i+1)
index

[2, 5]

In [ ]:
#Новое решение
t = torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])
peaks = (t[1:-1] > t[:-2]) & (t[1:-1] > t[2:])
indices = torch.where(peaks)[0]+1
indices, t[indices]

(tensor([2, 5]), tensor([7, 6]))

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [ ]:
df = torch.rand(100,)
val = 0
dist = (df - val).abs()
df[dist.argmin()]

tensor(0.0147)

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = torch.Tensor([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = torch.Tensor([[3, -1], [2, 1]])
C = torch.Tensor([[7, 21], [11, 8], [8, 4]])

$$A \cdot X \cdot B = -C <=> X = A^{-1} \cdot (-C) \cdot B^{-1}$$

In [ ]:
torch.linalg.inv(A) @ (-C) @ torch.linalg.inv(B)

tensor([[ 1.0000e+00, -1.1921e-07],
        [-2.0000e+00,  1.0000e+00],
        [ 3.0000e+00, -4.0000e+00]])

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

In [ ]:
a1 = torch.Tensor([3, -3, 0, 7])
a2 = torch.Tensor([2, 2, 4, 7])
a3 = torch.Tensor([1, 2, 3, 4])
a4 = torch.Tensor([5, -4, 1, 3])

In [ ]:
t = torch.stack((a1, a2, a3, a4), dim=0)
t

tensor([[ 3., -3.,  0.,  7.],
        [ 2.,  2.,  4.,  7.],
        [ 1.,  2.,  3.,  4.],
        [ 5., -4.,  1.,  3.]])

In [ ]:
torch.det(t)

tensor(2.4385e-05)

Т.к. матрица векторов вырождена, то система векторов линейно зависима. (детерминант = 0)

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами.

In [ ]:
t = torch.normal(0, 10, size=(1, 200))

In [ ]:
torch.histogram(t, bins=20)

torch.return_types.histogram(
hist=tensor([ 4.,  3.,  5.,  8.,  7., 11., 16., 12., 19., 22., 16., 21., 18., 13.,
        10.,  6.,  5.,  1.,  1.,  2.]),
bin_edges=tensor([-25.9983, -23.2300, -20.4618, -17.6935, -14.9253, -12.1571,  -9.3888,
         -6.6206,  -3.8523,  -1.0841,   1.6841,   4.4524,   7.2206,   9.9889,
         12.7571,  15.5253,  18.2936,  21.0618,  23.8301,  26.5983,  29.3666]))